const surpriseMePrompts = [
  
    "apple",
    "banana",
    "car",
    "bicycle",
    "table",
    "chair",
    "lamp",
    "book",
    "notebook",
    "pen",
    "laptop",
    "phone",
    "television",
    "refrigerator",
    "oven",
    "microwave",
    "washing machine",
    "dishwasher",
    "toaster",
    "blender",
    "fan",
    "air conditioner",
    "heater",
    "vacuum cleaner",
    "bed",
    "pillow",
    "blanket",
    "wardrobe",
    "drawer",
    "cupboard",
    "shelf",
    "picture frame",
    "mirror",
    "clock",
    "rug",
    "curtain",
    "door",
    "window",
    "desk",
    "monitor",
    "keyboard",
    "mouse",
    "backpack",
    "suitcase",
    "wallet",
    "watch",
    "glasses",
    "shoes",
    "jacket",
    "hat"

  ];

  export default surpriseMePrompts;